/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    BlockCheckbox: typeof import('./src/components/SettingDrawer/BlockCheckbox.vue')['default']
    BlockThemeColor: typeof import('./src/components/SettingDrawer/BlockThemeColor.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    FallbackPage: typeof import('./src/components/FallbackPage.vue')['default']
    HeaderActions: typeof import('./src/components/HeaderActions.vue')['default']
    LanguageToggle: typeof import('./src/components/LanguageToggle.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader/index.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingBlock: typeof import('./src/components/SettingDrawer/SettingBlock.vue')['default']
    SettingDrawer: typeof import('./src/components/SettingDrawer/index.vue')['default']
    SubMenu: typeof import('./src/components/SubMenu/index.vue')['default']
  }
}
